TrainingArguments:
  batch_size: 1024
  epochs: 1000
  lr: 0.01
  layers: [128,64]
  dropout: 0.3

EvaluationArguments: # Should agree with TrainingArguments 
  batch_size: 1024
  layers: [128,64] 
  dropout: 0.3
