artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  dataset_dir: artifacts/data/raw 
  source_URL: deepcontractor/car-price-prediction-challenge

data_cleaning:
  root_dir: artifacts/data
  raw_dataset_dir: artifacts/data/raw
  dataset_dir: artifacts/data/interim

data_transformation:
  root_dir: artifacts
  interim_dataset_dir: artifacts/data/interim
  dataset_dir: artifacts/data/processed
  label_encoder_dir: artifacts/encoders
  tensors_dim_dir: artifacts/tensors_dim

model_trainer:
  root_dir: artifacts/model
  processed_dataset_dir: artifacts/data/processed
  embed_dim_file_path: artifacts/tensors_dim/embedding_dim.pkl
  num_dim_file_path: artifacts/tensors_dim/num_dim.pkl
  model_dir: artifacts/model

model_evaluation:
  root_dir: artifacts/model
  model_file_path: artifacts/model/model.pth
  model_state_file_path: artifacts/model/model.pth
  embed_dim_file_path: artifacts/tensors_dim/embedding_dim.pkl
  num_dim_file_path: artifacts/tensors_dim/num_dim.pkl
  data_file_path: artifacts/data/processed/test.pth
  evaluation_results: artifacts/model
  